<main class="main lang-ru">
    <h2>ГЛАВНЫЙ РЕДАКТОР</h2>
    <p>Несмеянов Е. Е. – доктор философских наук, профессор, Заслуженный работник высшей школы Российской Федерации, Почётный работник Министерства образования Российской Федерации, заведующий кафедрой философии и мировых религий (Федеральное государственное бюджетное образовательное учреждение высшего образования «Донской государственный технический университет», г. Ростов-на-Дону)</p>
    <h2>РЕДАКЦИОННАЯ КОЛЛЕГИЯ</h2>
    <p>Говердовская Е. В. – заместитель главного редактора, доктор педагогических наук, профессор, заместитель директора по непрерывному образованию (Пятигорский медико-фармацевтический институт − филиал федерального государственного бюджетного образовательного учреждения высшего образования «Волгоградский государственный медицинский университет» Министерства здравоохранения Российской Федерации», г. Пятигорск);</p>
    <p>Абидова З.К.- доктор философии, заведующий кафедрой «Общественные науки», (Урченчский филилал Ташкентской медицинской академии, г. Ургенч);</p>
    <p>Акаев В. Х. – доктор философских наук, профессор, главный научный сотрудник (Федеральное государственное бюджетное учреждение науки Комплексный научно-исследовательский институт им. Х.И. Ибрагимова Российской академии наук, г. Грозный);</p>
    <p>Арябкина И. В. - доктор педагогических наук, профессор (Федеральное государственное бюджетное образовательное учреждение высшего образования «Ульяновский государственный педагогический университет имени И. Н. Ульянова», г. Ульяновск);</p>
    <p>Бондаренко А. В.  кандидат философских наук, доцент, заместитель заведующего кафедрой по учебной и научной работе кафедры «Философия» (Федеральное государственное бюджетное образовательное учреждение высшего образования «Уфимский государственный нефтяной технический университет», г. Уфа);</p>
    <p>Верещагина А. В.−доктор социологических наук, профессор кафедры теоретической социологии и методологии региональных исследований Института социологии и регионоведения (Федеральное государственное автономное образовательное учреждение высшего образования «Южный федеральный университет», г. Ростов-на-Дону);</p>
    <p>Гончаров В. Н.−доктор философских наук, профессор кафедры философии Гуманитарного института (Федеральное государственное автономное образовательное учреждение высшего образования "Северо-Кавказский федеральный университет», г. Ставрополь);</p>
    <p>Дохоян А. М. – кандидат психологических наук, доцент, заведующий кафедрой социальной, специальной педагогики и психологии, (Федеральное государственное бюджетное образовательное учреждение высшего образования «Армавирский государственный педагогический университет», г. Армавир);</p>
    <p>Каргиева З. К. - доктор педагогических наук, профессор, профессор кафедры теории и технологии социальной работы юридического факультета (Федеральное государственное бюджетное образовательное учреждение высшего образования "Чеченский государственный университет им. А.А.Кадырова", г. Грозный);</p>
    <p>Касьянов В. В.−доктор социологических, доктор исторических наук, профессор, декан факультета журналистики, заведующий кафедрой истории России (Федеральное государственное бюджетное образовательное учреждение высшего образования «Кубанский государственный университет», г. Краснодар);</p>
    <p>Ладыгина О. В. – доктор философских наук, доцент, Межгосударственное образовательное учреждение высшего образования «Российско-таджикский Славянский Университет»(г. Душанбе);</p>
    <p>Лукацкий М. А. − член-корреспондент РАО, доктор педагогических наук, профессор, почетный работник общего образования Российской Федерации, Научный руководитель лаборатории теоретической педагогики ИТИП РАО, заведующий кафедрой психологии и педагогики (Государственное бюджетное образовательное учреждение высшего образования «Московский государственный медико-стоматологический университет имени А. И. Евдокимова» Министерства здравоохранения Российской Федерации, г. Москва);</p>
    <p>Осадчая Г. И. – доктор социологических наук, профессор, заместитель директора по научной работе (Институт социально-политических исследований Российской академии наук, г. Москва);</p>
    <p>Матяш Т. П. – доктор философских наук, профессор, профессор-консультант кафедры философии религии и религиоведения (Федеральное государственное автономное образовательное учреждение высшего образования «Южный федеральный университет», г. Ростов-на-Дону);</p>
    <p>Пусько В. С. – доктор философских наук, профессор, заведующий кафедрой политологии факультета социальных и гуманитарных наук (Федеральное государственное бюджетное образовательное учреждение высшего образования «Московский государственный технический университет имени Н.Э. Баумана (национальный исследовательский университет)», г. Москва);</p>
    <p>Ратиев В. В. − доктор социологических наук, директор(Филиал частного образовательного учреждения высшего образования «Московский университет имени С.Ю. Витте» в г. Краснодар, г. Краснодар);</p>
    <p>Розин М. Д. – доктор философских наук, профессор, директор Северо-Кавказского научного центра высшей школы (Федеральное государственное автономное образовательное учреждение высшего образования «Южный федеральный университет», г. Ростов-на-Дону);</p>
    <p>Ромаева Н. Б. – доктор педагогических наук, профессор кафедры педагогики и педагогических технологий Педагогического института (Федеральное государственное автономное образовательное учреждение высшего образования "Северо-Кавказский федеральный университет», г. Ставрополь);</p>
    <p>Самыгин С. И.−доктор социологических наук, профессор кафедры "Управления персоналом и социологии" (Федеральное государственное бюджетное образовательное учреждение высшего образования «Ростовский государственный экономический университет», г. Ростов-на-Дону);</p>
    <p>Сущий С. Я. – доктор социологических наук, доцент, главный научный сотрудник Института социально-экономических и гуманитарных исследований (Южный научный центр Российской академии наук, г. Ростов-на-Дону);</p>
    <p>Тен Ю. П. – доктор философских наук, доцент, профессор Департамента менеджмента Финансового университета при Правительстве Российской Федерации (Федеральное государственное образовательное бюджетное учреждение высшего образования «Финансовый университет при Правительстве Российской Федерации» (Финансовый университет) г. Москва);</p>
    <p>Финько М. В. – доктор философских наук, директор конгрессно-выставочного центра (Федеральное государственное бюджетное образовательное учреждение высшего образования «Донской государственный технический университет», г. Ростов-на-Дону);</p>
    <p>Хараева Л. А. - доктор педагогических наук, профессор, профессор кафедры английского языка (Федеральное государственное бюджетное образовательное учреждение высшего образования «Кабардино-Балкарский государственный университет им. Х. М. Бербекова», г. Нальчик);</p>
    <p>Шингаров Г. Х. – доктор философских наук, профессор кафедры "Философия" (Негосударственное аккредитованное частное образовательное учреждение высшего профессионального образования Современная гуманитарная академия, г. Москва);</p>
    <p>Щербакова Л. И. − доктор социологических наук, профессор, профессор кафедры «Социология и психология» (Федеральное государственное бюджетное образовательное учреждение высшего образования «Южно-Российский государственный политехнический университет  М. И. Платова, г. Новочеркасск).</p>
</main>
<main class="main lang-en">
    <h2>EDITOR-IN-CHIEF</h2>
    <p>Nesmeyanov E. E. – Doctor of Philosophy, Professor, Honored Worker of Higher Education of the Russian Federation, Honorary Worker of the Ministry of Education of the Russian Federation, Head of the Department of Philosophy and World Religions (Federal State Budgetary Educational Institution of Higher Education "Don State Technical University", Rostov-on-Don)</p>
    <h2>EDITORIAL BOARD</h2>
    <p>Goverdovskaya E. V. – Deputy Editor-in-Chief, Doctor of Pedagogical Sciences, Professor, Deputy Director for Continuing Education (Pyatigorsk Medical and Pharmaceutical Institute − branch of the Federal State Budgetary Educational Institution of Higher Education "Volgograd State Medical University" of the Ministry of Health of the Russian Federation", Pyatigorsk)</p>
    <p>Abidova Z.K. - Doctor of Philosophy, Head of the Department of "Social Sciences", (Urchench branch of the Tashkent Medical Academy, Urgench);</p>
    <p>Akaev V. H. – Doctor of Philosophy, Professor, Chief Researcher (Federal State Budgetary Institution of Science Complex Research Institute named after H.I. Ibragimov of the Russian Academy of Sciences, Grozny);</p>
    <p>Aryabkina I. V. - Doctor of Pedagogical Sciences, Professor (Federal State Budgetary Educational Institution of Higher Education "Ulyanovsk State Pedagogical University named after I. N. Ulyanov", Ulyanovsk);</p>
    <p>Bondarenko A.V., Candidate of Philosophical Sciences, Associate Professor, Deputy Head of the Department for Academic and Scientific Work of the Department of Philosophy (Federal State Budgetary Educational Institution of Higher Education "Ufa State Petroleum Technical University", Ufa);</p>
    <p>Vereshchagina A.V.−Doctor of Sociology, Professor of the Department of Theoretical Sociology and Methodology of Regional Studies at the Institute of Sociology and Regional Studies (Federal State Autonomous Educational Institution of Higher Education "Southern Federal University", Rostov-on-Don);</p>
    <p>Goncharov V. N.−Doctor of Philosophy, Professor of the Department of Philosophy of the Humanities Institute (Federal State Autonomous Educational Institution of Higher Education "North Caucasus Federal University", Stavropol);</p>
    <p>Dokhoyan A.M. – Candidate of Psychological Sciences, Associate Professor, Head of the Department of Social, Special Pedagogy and Psychology, (Federal State Budgetary Educational Institution of Higher Education "Armavir State Pedagogical University", Armavir);</p>
    <p>Kargieva Z. K. - Doctor of Pedagogical Sciences, Professor, Professor of the Department of Theory and Technology of Social Work of the Faculty of Law (Federal State Budgetary Educational Institution of Higher Education "A.A.Kadyrov Chechen State University", Grozny);</p>
    <p>Kasyanov V. V.−Doctor of Sociology, Doctor of Historical Sciences, Professor, Dean of the Faculty of Journalism, Head of the Department of Russian History (Federal State Budgetary Educational Institution of Higher Education "Kuban State University", Krasnodar);</p>
    <p>Ladygina O. V. – Doctor of Philosophy, Associate Professor, Interstate Educational Institution of Higher Education "Russian-Tajik Slavic University" (Dushanbe);</p>
    <p>Lukatsky M. A. − Corresponding Member of RAO, Doctor of Pedagogical Sciences, Professor, Honorary Worker of General Education of the Russian Federation, Scientific Director of the Laboratory of Theoretical Pedagogy of ITIP RAO, Head of the Department of Psychology and Pedagogy (State Budgetary Educational Institution of Higher Education "Moscow State Medical and Dental University named after A. I. Evdokimov" of the Ministry of Health of the Russian Federation, Moscow Moscow);</p>
    <p>Osadchaya G. I. – Doctor of Sociology, Professor, Deputy Director for Research (Institute of Socio-Political Studies of the Russian Academy of Sciences, Moscow);</p>
    <p>T. P. Matyash – Doctor of Philosophy, Professor, Professor-Consultant of the Department of Philosophy of Religion and Religious Studies (Federal State Autonomous Educational Institution of Higher Education "Southern Federal University", Rostov-on-Don);</p>
    <p>Pusko V. S. – Doctor of Philosophy, Professor, Head of the Department of Political Science of the Faculty of Social Sciences and Humanities (Federal State Budgetary Educational Institution of Higher Education "Bauman Moscow State Technical University (National Research University)", Moscow);</p>
    <p>Ratiev V. V. − Doctor of Sociology, Director (Branch of the private educational institution of Higher education "S.Y. Witte Moscow University" in Krasnodar, Krasnodar);</p>
    <p>Rozin M. D. – Doctor of Philosophy, Professor, Director of the North Caucasus Higher School Research Center (Federal State Autonomous Educational Institution of Higher Education "Southern Federal University", Rostov-on-Don);</p>
    <p>Romayeva N. B. – Doctor of Pedagogical Sciences, Professor of the Department of Pedagogy and Pedagogical Technologies of the Pedagogical Institute (Federal State Autonomous Educational Institution of Higher Education "North Caucasus Federal University", Stavropol);</p>
    <p>Samygin S. I.−Doctor of Sociology, Professor of the Department of Personnel Management and Sociology (Federal State Budgetary Educational Institution of Higher Education "Rostov State University of Economics", Rostov-on-Don);</p>
    <p>Suschiy S. Ya. – Doctor of Sociology, Associate Professor, Chief Researcher at the Institute of Socio-Economic and Humanitarian Studies (Southern Scientific Center of the Russian Academy of Sciences, Rostov-on-Don);</p>
    <p>Ten Yu. P. – Doctor of Philosophy, Associate Professor, Professor of the Department of Management of the Financial University under the Government of the Russian Federation (Federal State Educational Budgetary Institution of Higher Education "Financial University under the Government of the Russian Federation" (Financial University) Moscow);</p>
    <p>M. V. Finko – Doctor of Philosophy, Director of the Congress and Exhibition Center (Federal State Budgetary Educational Institution of Higher Education "Don State Technical University", Rostov-on-Don);</p>
    <p>Kharaeva L. A. - Doctor of Pedagogical Sciences, Professor, Professor of the Department of English (Federal State Budgetary Educational Institution of Higher Education "Kabardino-Balkarian State University named after H. M. Berbekov", Nalchik);</p>
    <p>Shingarov G. H. – Doctor of Philosophy, Professor of the Department of Philosophy (Non-governmental accredited private educational institution of higher professional education Modern Humanitarian Academy, Moscow);</p>
    <p>Shcherbakova L. I. − Doctor of Sociological Sciences, Professor, Professor of the Department of Sociology and Psychology (Federal State Budgetary Educational Institution of Higher Education "M. I. Platov South Russian State Polytechnic University, Novocherkassk).</p>
</main>